export { 
  SUCCESSFUL_LOGIN, SUCCESSFUL_ADD_ARTICLE, SUCCESSFUL_EDIT_ARTICLE, SUCCESSFUL_DELETE_ARTICLE,
  SUCCESSFUL_PWD_RECOVER, SUCCESSFUL_ADDING, SUCCESSFUL_DELETE, SUCCESSFUL_EDIT
 } from './notices'
 
 export { ERROR_LOGIN, 
  ERROR_PWD_RECOVER, ERROR_ARTICLE_ADD, ERROR_ARTICLE_DELETE, ERROR_ARTICLE_EDIT,
   ERROR_TAG_ADDIND , ERROR_TAG_DELETE, ERROR_TAG_EDIT
 } from './errors'

 
 export { EMPTY_FIELD, 
  WRONG_TYPE, 
  MANY_SYMBOLS, 
  FEW_SYMBOLS, 
  NOT_EMAIL, 
  PASSWORD_ERROR
 } from './inputValidMasseges'